name: Build coolname container


on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - Containerfile
      - requirements.txt
      - gunicorn_conf.py
      - flaskcoolname/**
    tags:
      - v*


env:
  image: ghcr.io/${{ github.repository }}


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gather metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.image }}
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch,enable={{is_default_branch}}
          flavor: |
            latest=auto

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Containerfile
          platforms: linux/amd64,linux/arm64/v8
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # cache-from: type=registry,ref=user/app:buildcache
          # cache-to: type=registry,ref=user/app:buildcache,mode=max
          push: true


# The end.
