name: Remove untagged images


on:
  workflow_dispatch:
  schedule:
    - cron: "30 2 */10 * *"


env:
  image: ghcr.io/${{ github.repository }}


jobs:
  remove-package-versions:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - uses: Chizkiyahu/delete-untagged-ghcr-action@v3
        with:
          token: ${{ github.token }}
          untagged_only: true
          except_untagged_multiplatform: true


# The end.
