name: Remove untagged images


on:
  workflow_dispatch:
  schedule:
    - cron: "30 2 */10 * *"


env:
  image: ghcr.io/${{ github.repository }}


jobs:
  remove-package-versions:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry with PAT_TOKEN
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - uses: Chizkiyahu/delete-untagged-ghcr-action@v3
        with:
          token: ${{ github.token }}
          package_name: flask-coolname
          owner_type: user
          untagged_only: true
          except_untagged_multiplatform: true


# The end.
